### ISSUE TITLE
Aggregator crashes after connecting to coordinator (macos, cargo)

### ISSUE THREAD

**Issue by janpetschexain** [xainag/xain-fl#317]
Running a coordinator with
```
cargo run --bin coordinator -- -c ../configs/dev-coordinator.toml
```
followed by an aggregator with
```
cargo run --bin aggregator -- -c ../configs/dev-aggregator.toml
```
leads to a crash on macOS due to some python import error:
```
X-MBP-010:rust jan.petsche$ cargo run --bin aggregator -- -c ../configs/dev-aggregator.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/aggregator -c ../configs/dev-aggregator.toml`
[2020-03-17T13:54:03Z TRACE mio::poll] registering with poller
[2020-03-17T13:54:03Z TRACE mio::poll] registering with poller
[2020-03-17T13:54:03Z TRACE mio::sys::unix::kqueue] registering; token=Token(1); interests=Readable | Writable | Error | Hup
[2020-03-17T13:54:03Z TRACE mio::sys::unix::kqueue] registering; token=Token(0); interests=Readable | Writable | Error | Hup
[2020-03-17T13:54:03Z INFO  stubborn_io::tokio::io] Initial connection succeeded.
[2020-03-17T13:54:03Z TRACE tokio_util::codec::framed_write] flushing framed transport
[2020-03-17T13:54:03Z TRACE tokio_util::codec::framed_write] framed transport flushed
[2020-03-17T13:54:03Z TRACE mio::poll] registering with poller
[2020-03-17T13:54:03Z TRACE mio::sys::unix::kqueue] registering; token=Token(2); interests=Readable | Writable | Error | Hup
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::service] polling AggregatorService
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::service] polling RPC requests
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::rpc] polling RpcRequestsMux
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::rpc] no RequestStream, polling the RequestStream receiver
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::service] polling API requests
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::service] polling ApiRx
[2020-03-17T13:54:03Z TRACE mio::poll] registering with poller
[2020-03-17T13:54:03Z TRACE mio::sys::unix::kqueue] registering; token=Token(3); interests=Readable | Writable | Error | Hup
[2020-03-17T13:54:03Z INFO  xain_fl::aggregator::api] starting HTTP server on localhost:8082
[2020-03-17T13:54:03Z INFO  warp::server] listening with custom incoming
Traceback (most recent call last):
  File "/Users/jan.petsche/Documents/AI/FL-RUST/coordinator-rs/python/aggregators/xain_aggregators/weighted_average.py", line 2, in <module>
    import pickle
  File "/Users/jan.petsche/.pyenv/versions/3.7.2/lib/python3.7/pickle.py", line 33, in <module>
    from struct import pack, unpack
  File "/Users/jan.petsche/.pyenv/versions/3.7.2/lib/python3.7/struct.py", line 13, in <module>
    from _struct import *
ImportError: dlopen(/Users/jan.petsche/.pyenv/versions/3.7.2/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so, 2): Symbol not found: __PyFloat_Pack2
  Referenced from: /Users/jan.petsche/.pyenv/versions/3.7.2/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/jan.petsche/.pyenv/versions/3.7.2/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so
[2020-03-17T13:54:03Z ERROR xain_fl::aggregator::py_aggregator] py_aggregator failure: failed to load python module `xain_aggregators.weighted_average`
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::service] polling AggregatorService
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::service] polling RPC requests
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::rpc] polling RpcRequestsMux
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::rpc] no RequestStream, polling the RequestStream receiver
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::service] polling API requests
[2020-03-17T13:54:03Z TRACE xain_fl::aggregator::service] polling ApiRx
[2020-03-17T13:54:03Z TRACE mio::poll] deregistering handle with poller
[2020-03-17T13:54:03Z INFO  aggregator] shutting down: Aggregator terminated
[2020-03-17T13:54:03Z TRACE tokio_util::codec::framed_write] flushing framed transport
[2020-03-17T13:54:03Z TRACE tokio_util::codec::framed_write] framed transport flushed
[2020-03-17T13:54:03Z INFO  tarpc::rpc::client::channel] Shutdown: write half closed, and no requests in flight.
[2020-03-17T13:54:03Z TRACE mio::poll] deregistering handle with poller
[2020-03-17T13:54:03Z TRACE mio::poll] deregistering handle with poller
[2020-03-17T13:54:03Z TRACE mio::poll] deregistering handle with poller
```

**Comment by Robert-Steiner** [comment]
Closed by #365
